#spring:
#  profiles:
#    default: local
---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    producer:
      bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
#      group-id: jisu

test:
  topic: embedded-test-topic

schema:
  registry:
    url: http://localhost:8081
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: prod
