# MySQL ?????? ??
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onion-db
    username: onion-user
    password: onion1!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      connection-test-query: SELECT 1
      max-lifetime: 1800000
  # JPA ??
  jpa:
    hibernate:
      ddl-auto: update # create, update, validate, none
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

# log
logging:
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
