# MySQL ?????? ??
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onion-db
    username: onion-user
    password: onion1!
    driver-class-name: com.mysql.cj.jdbc.Driver
# JPA ??
  jpa:
    hibernate:
      ddl-auto: update # create, update, validate, none
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

# log
logging:
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
