-- create table person (
--     id bigint primary key auto_increment,
--     name varchar(255),
--     age varchar(255),
--     address varchar(255)
-- );

-- insert into person(name, age, address)
--     values('김지수', '28', '안산');
-- insert into person(name, age, address)
--     values('김지수', '28', '안산');
-- insert into person(name, age, address)
--     values('김지수', '28', '안산');