spring:
  data:
    mongodb:
      uri: URI
      database: test

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: trace

#logging:
#  level:
#    org.springframework.data.mongodb: DEBUG
#    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


