server.port: 7002
springdoc:
  swagger-ui:
    enabled: true
    operations-sorter: method
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Spring_Chatting
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
token:
  secret-key: "SECRET"
  refresh-secret-key: "REFRESH_SECRET"
  token-time: 300
  refresh-token-time: 300
