#spring:
#  data:
#    mongodb:
#      uri: URI
#      database: test

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: trace
    root: debug

#logging:
#  level:
#    org.springframework.data.mongodb: DEBUG
#    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

com:
  example:
    dev:
      uri: http://localhost:8080
      database: test