## Only for Local Test
## H2
#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
## DataSource
#  datasource:
#    driver-class-name: org.h2.Driver
#    url:jdbc:h2:mem:test
#    username: sa
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#
#kafka:
#  clusters:
#    bootstrapservers: localhost:9092
#logging:
#  topic: logging.out.stdout
#membership:
#  service:
#    endpoint: http://localhost:8081
