spring:
  datasource:
    hikari:
      primary:
        driver-class-name: org.h2.Driver
        jdbc-url: jdbc:h2:mem:~/primary
        username: sa
        password:
      second:
        driver-class-name: org.h2.Driver
        jdbc-url: jdbc:h2:mem:~/second
        username: sa
        password:
  jpa:
    database: h2
#    hibernate:
#      ddl-auto: create
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
    open-in-view: false

  main:
    allow-bean-definition-overriding: true
