#version: '3.3'
#networks:
#  default:
#    external: name:
#    kafka services: cp-schema-registry: container_name: schema-registry environment: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: ${BOOTSTRAP_SERVERS} SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081 image: confluentinc/cp-schema-registry:5.1.0 ports: - 8081:8081 cp-kafka-rest: container_name: kafka-rest environment: KAFKA_REST_BOOTSTRAP_SERVERS: ${BOOTSTRAP_SERVERS} KAFKA_REST_LISTENERS: http://0.0.0.0:8082 KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry:8081 KAFKA_REST_HOST_NAME: kafka-rest image: confluentinc/cp-kafka-rest:5.1.0 depends_on: - cp-schema-registry ports: - 8082:8082

version: '3'

networks:
  kafka_network:
    driver: bridge
    name: kafka

services:
  zookeeper:
    platform: linux/amd64
    #    image: 'arm64v8/zookeeper:3.8'
    image: 'zookeeper:latest'
    networks:
      - kafka_network
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_TLS_CLIENT_AUTH=none
      - ZOO_TLS_QUORUM_CLIENT_AUTH=none

  kafka:
    platform: linux/amd64
    #    image: 'bitnami/kafka:3.4.0'
    image: 'bitnami/kafka:latest'
    networks:
      - kafka_network
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=LC://kafka:29092,LX://kafka:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=LC://kafka:29092,LX://${DOCKER_HOST_IP:-localhost}:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=LC:PLAINTEXT,LX:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=LC
    depends_on:
      - zookeeper

  kafka-ui:
    platform: linux/amd64
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    networks:
      - kafka_network
    ports:
      - "8989:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - zookeeper
      - kafka

  cp-schema-registry:
    container_name: kafka-schema-registry
    image: confluentinc/cp-schema-registry
    networks:
      - kafka_network
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
#      SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: NONE
      SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: BACKWARD
#      SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: FULL
#      SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: FORWARD
    ports:
      - 8081:8081
    depends_on:
      - zookeeper
      - kafka

#  cp-kafka-rest:
#    container_name: kafka-rest
#    image: confluentinc/cp-kafka-rest:5.1.0
#    networks:
#      - kafka_network
#    environment:
#      KAFKA_REST_BOOTSTRAP_SERVERS: ${BOOTSTRAP_SERVERS}
#      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
#      KAFKA_REST_SCHEMA_REGISTRY_URL: http://kafka-schema-registry:8081
#      KAFKA_REST_HOST_NAME: kafka-rest
#    depends_on:
#      - zookeeper
#      - kafka
#      - cp-schema-registry
#    ports:
#      - 8082:8082
